version: '3'
services:
  crawler:
    image: victor/google-support-crawler
    command: ./wait-for-postgres.sh database npm run crawler
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database
  api:
    image: victor/google-support-crawler
    command: ./wait-for-postgres.sh database npm run server
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database
    ports:
      - '3000:3000'
  database:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - ALLOW_IP_RANGE='0.0.0.0/0'
    volumes:
      - './pgdata:/var/lib/postgresql/data/pgdata'
